language: rust
rust:
  - stable
cache:
  cargo: false
  directories:
    - $TRAVIS_BUILD_DIR/libsodium
dist: xenial
sudo: required
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - ./.travis.sh

script:
  - cargo build
  - cargo test --features storage-file

# only build on master and stable branches
branches:
  only:
    - master
    - stable

notifications:
  email:
    on_success: never
