language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
  directories:
    - $TRAVIS_BUILD_DIR/libsodium
dist: trusty
sudo: required
matrix:
  allow_failures:
    - rust: nightly

before_install:
  - ./.travis.sh

script:
  - cargo build
  - cargo test

# only build on master and stable branches
branches:
  only:
    - master
    - stable

notifications:
  email:
    on_success: never
