[package]
name = "zbox"
version = "0.6.1"
authors = ["Bo Lu"]
description = "Zbox is a zero-details, privacy-focused embeddable file system."
documentation = "https://docs.rs/zbox"
homepage = "https://github.com/zboxfs/zbox"
repository = "https://github.com/zboxfs/zbox"
readme = "README.md"
keywords = ["filesystem", "crypto", "security", "privacy", "storage"]
categories = ["filesystem", "cryptography"]
license = "Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "zboxfs/zbox" }

[lib]
name = "zbox"
crate-type = ["rlib", "dylib", "staticlib"]

[features]
default = []

# performance test compilation flag
test-perf = []

# ffi compilation flag
ffi = []

# faulty storage for random io error test
storage-faulty = ["lazy_static"]

# sqlite storage
storage-sqlite = ["libsqlite3-sys"]

# redis storage
storage-redis = ["redis"]

# zbox storage
storage-zbox = ["reqwest"]

[dependencies]
bytes = "0.4.9"
env_logger = "0.5.9"
log = "0.4.4"
lz4 = "1.22.0"
rmp-serde = "0.13.7"
serde = "1.0.43"
serde_derive = "1.0.43"
lazy_static = { version = "1.1.0", optional = true }
libsqlite3-sys = { version = "0.9.3", optional = true }
redis = { version = "0.9.0", optional = true }
reqwest  = { version = "0.9.0", optional = true }

[dependencies.linked-hash-map]
version = "0.5.1"
features = ["serde_impl"]

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.10.1"
android_log = "0.1.3"

[dev-dependencies]
tempdir = "0.3.7"
rand = "0.5"

[build-dependencies]
pkg-config = "0.3.14"
