[package]
name = "zbox"
version = "0.1.4"
authors = ["Bo Lu"]
description = "Zbox is a zero-details, privacy-focused embeddable file system."
documentation = "https://docs.rs/zbox"
homepage = "https://github.com/zboxfs/zbox"
repository = "https://github.com/zboxfs/zbox"
readme = "README.md"
keywords = ["filesystem", "crypto", "security", "privacy", "storage"]
categories = ["filesystem", "cryptography"]
license = "Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "zboxfs/zbox" }

[lib]
name = "zbox"
crate-type = ["rlib", "dylib"]

[dependencies]
bytes = "0.4.6"
env_logger = "0.5.2"
log = "0.4.1"
rmp-serde = "0.13.7"
serde = "1.0.27"
serde_derive = "1.0.27"
lz4 = "1.22.0"

[dependencies.linked-hash-map]
version = "0.5.0"
features = ["serde_impl"]

[dev-dependencies]
tempdir = "0.3.5"
rand = "0.4.1"

[build-dependencies]
pkg-config = "0.3.9"
