[package]
name = "zbox"
version = "0.1.3"
authors = ["Bo Lu"]
description = "Zbox is a zero-details, privacy-focused embeddable file system."
documentation = "https://docs.rs/zbox"
homepage = "https://github.com/zboxfs/zbox"
repository = "https://github.com/zboxfs/zbox"
readme = "README.md"
keywords = ["filesystem", "crypto", "security", "privacy", "storage"]
categories = ["filesystem", "cryptography"]
license = "Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "zboxfs/zbox" }

[lib]
name = "zbox"
crate-type = ["rlib", "dylib"]

[dependencies]
bytes = "^0.4"
env_logger = "~0.4"
log = "~0.3"
rmp-serde = "~0.13"
serde = "~1.0"
serde_derive = "~1.0"
lz4 = "~1.21"

[dependencies.linked-hash-map]
version = "~0.5"
features = ["serde_impl"]

[dev-dependencies]
tempdir = "~0.3"

[build-dependencies]
pkg-config = "~0.3"
