[package]
name = "zbox"
version = "0.6.1"
authors = ["Bo Lu"]
description = "Zbox is a zero-details, privacy-focused embeddable file system."
documentation = "https://docs.rs/zbox"
homepage = "https://github.com/zboxfs/zbox"
repository = "https://github.com/zboxfs/zbox"
readme = "README.md"
keywords = ["filesystem", "crypto", "security", "privacy", "storage"]
categories = ["filesystem", "cryptography"]
license = "Apache-2.0"
build = "build.rs"

[badges]
travis-ci = { repository = "zboxfs/zbox" }

[lib]
name = "zbox"
crate-type = ["rlib", "dylib", "staticlib"]

[features]
default = []

# performance test compilation flag
test-perf = []

# ffi compilation flag
ffi = []

# faulty storage for random io error test
storage-faulty = ["lazy_static"]

# sqlite storage
storage-sqlite = ["libsqlite3-sys"]

# redis storage
storage-redis = ["redis"]

# zbox storage with native transport
storage-zbox-native = ["storage-zbox", "reqwest"]

# zbox storage with jni transport
storage-zbox-jni = ["storage-zbox", "jni", "lazy_static"]

# zbox storage base dependencies
storage-zbox = ["http", "serde_json"]

[dependencies]
bytes = "0.4.10"
env_logger = "0.6.0"
log = "0.4.6"
lz4 = "1.23.0"
rmp-serde = "0.13.7"
serde = "1.0.80"
serde_derive = "1.0.80"
lazy_static = { version = "1.2.0", optional = true }
libsqlite3-sys = { version = "0.10.0", optional = true }
redis = { version = "0.9.1", optional = true }
http  = { version = "0.1.14", optional = true }
serde_json = { version = "1.0.33", optional = true }
reqwest  = { version = "0.9.5", optional = true }
jni = { version = "0.10.2", optional = true }

[dependencies.linked-hash-map]
version = "0.5.1"
features = ["serde_impl"]

[target.'cfg(target_os = "android")'.dependencies]
android_log = "0.1.3"

[dev-dependencies]
tempdir = "0.3.7"
rand = "0.6"
rand_xorshift = "0.1.0"

[build-dependencies]
pkg-config = "0.3.14"
