name: Rust

on: [push]

env:
  LIBSODIUM: libsodium-1.0.17
  LIBSODIUM_INSTALL: $HOME
  SODIUM_LIB_DIR: $LIBSODIUM_INSTALL/lib

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Cache libsodium
      id: cache-libsodium
      uses: actions/cache@v1
      with:
        path: $SODIUM_LIB_DIR
        key: ${{ runner.os }}-$LIBSODIUM
        
    - name: Build libsodium
      if: steps.cache-libsodium.outputs.cache-hit != 'true'
      run: |
        wget -nv https://download.libsodium.org/libsodium/releases/$LIBSODIUM.tar.gz
        tar -xzf $LIBSODIUM.tar.gz
        echo $LIBSODIUM_INSTALL
        cd $LIBSODIUM && ./configure --prefix=$LIBSODIUM_INSTALL && make && sudo make install
      
    - name: Build ZboxFS
      run: cargo build
      
    - name: Run ZboxFS tests
      run: cargo test
    
    - name: Run ZboxFS file storage tests
      run: cargo test --features storage-file
