name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Build libsodium
      run: |
        pwd
      working-directory: $GITHUB_WORKSPACE
      env:
        LIBSODIUM: libsodium-1.0.17
        LIBSODIUM-DIR: $GITHUB_WORKSPACE/libsodium
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
