name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Cache libsodium
      id: cache-libsodium
      uses: actions/cache@v1
      with:
        path: libsodium-1.0.17
        key: {{ runner.os }}-libsodium
        
    - name: Build libsodium
      if: steps.cache-libsodium.outputs.cache-hit != 'true'
      run: |
        wget -nv https://download.libsodium.org/libsodium/releases/$LIBSODIUM.tar.gz
        tar -xzf $LIBSODIUM.tar.gz
        cd $LIBSODIUM && ./configure --prefix=/usr && make && sudo make install
      env:
        LIBSODIUM: libsodium-1.0.17
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
